/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as ProfilRouteImport } from './routes/profil'
 import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as FiscaliteRouteImport } from './routes/fiscalite'
import { Route as EcrituresRouteImport } from './routes/ecritures'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as BanqueRouteImport } from './routes/banque'
import { Route as AideRouteImport } from './routes/aide'
import { Route as ActeursRouteImport } from './routes/acteurs'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscaliteRoute = FiscaliteRouteImport.update({
  id: '/fiscalite',
  path: '/fiscalite',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrituresRoute = EcrituresRouteImport.update({
  id: '/ecritures',
  path: '/ecritures',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const BanqueRoute = BanqueRouteImport.update({
  id: '/banque',
  path: '/banque',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const ActeursRoute = ActeursRouteImport.update({
  id: '/acteurs',
  path: '/acteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acteurs': typeof ActeursRoute
  '/aide': typeof AideRoute
  '/banque': typeof BanqueRoute
  '/caisse': typeof CaisseRoute
  '/ecritures': typeof EcrituresRoute
  '/fiscalite': typeof FiscaliteRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/profil': typeof ProfilRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acteurs': typeof ActeursRoute
  '/aide': typeof AideRoute
  '/banque': typeof BanqueRoute
  '/caisse': typeof CaisseRoute
  '/ecritures': typeof EcrituresRoute
  '/fiscalite': typeof FiscaliteRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/profil': typeof ProfilRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acteurs': typeof ActeursRoute
  '/aide': typeof AideRoute
  '/banque': typeof BanqueRoute
  '/caisse': typeof CaisseRoute
  '/ecritures': typeof EcrituresRoute
  '/fiscalite': typeof FiscaliteRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/profil': typeof ProfilRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acteurs'
    | '/aide'
    | '/banque'
    | '/caisse'
    | '/ecritures'
    | '/fiscalite'
    | '/parametres'
    | '/produits'
    | '/profil'
    | '/tresorerie'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acteurs'
    | '/aide'
    | '/banque'
    | '/caisse'
    | '/ecritures'
    | '/fiscalite'
    | '/parametres'
    | '/produits'
    | '/profil'
    | '/tresorerie'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/acteurs'
    | '/aide'
    | '/banque'
    | '/caisse'
    | '/ecritures'
    | '/fiscalite'
    | '/parametres'
    | '/produits'
    | '/profil'
    | '/tresorerie'
    | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActeursRoute: typeof ActeursRoute
  AideRoute: typeof AideRoute
  BanqueRoute: typeof BanqueRoute
  CaisseRoute: typeof CaisseRoute
  EcrituresRoute: typeof EcrituresRoute
  FiscaliteRoute: typeof FiscaliteRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  ProfilRoute: typeof ProfilRoute
  TresorerieRoute: typeof TresorerieRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscalite': {
      id: '/fiscalite'
      path: '/fiscalite'
      fullPath: '/fiscalite'
      preLoaderRoute: typeof FiscaliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecritures': {
      id: '/ecritures'
      path: '/ecritures'
      fullPath: '/ecritures'
      preLoaderRoute: typeof EcrituresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banque': {
      id: '/banque'
      path: '/banque'
      fullPath: '/banque'
      preLoaderRoute: typeof BanqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acteurs': {
      id: '/acteurs'
      path: '/acteurs'
      fullPath: '/acteurs'
      preLoaderRoute: typeof ActeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActeursRoute: ActeursRoute,
  AideRoute: AideRoute,
  BanqueRoute: BanqueRoute,
  CaisseRoute: CaisseRoute,
  EcrituresRoute: EcrituresRoute,
  FiscaliteRoute: FiscaliteRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  ProfilRoute: ProfilRoute,
  TresorerieRoute: TresorerieRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
