/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as RecouvrementRouteImport } from './routes/recouvrement'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ImpayesRouteImport } from './routes/impayes'
import { Route as EcrituresRouteImport } from './routes/ecritures'
import { Route as CommerciauxRouteImport } from './routes/commerciaux'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecouvrementRoute = RecouvrementRouteImport.update({
  id: '/recouvrement',
  path: '/recouvrement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpayesRoute = ImpayesRouteImport.update({
  id: '/impayes',
  path: '/impayes',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrituresRoute = EcrituresRouteImport.update({
  id: '/ecritures',
  path: '/ecritures',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerciauxRoute = CommerciauxRouteImport.update({
  id: '/commerciaux',
  path: '/commerciaux',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/aide': typeof AideRoute
  '/clients': typeof ClientsRoute
  '/commerciaux': typeof CommerciauxRoute
  '/ecritures': typeof EcrituresRoute
  '/impayes': typeof ImpayesRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/regions': typeof RegionsRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/aide': typeof AideRoute
  '/clients': typeof ClientsRoute
  '/commerciaux': typeof CommerciauxRoute
  '/ecritures': typeof EcrituresRoute
  '/impayes': typeof ImpayesRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/regions': typeof RegionsRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/aide': typeof AideRoute
  '/clients': typeof ClientsRoute
  '/commerciaux': typeof CommerciauxRoute
  '/ecritures': typeof EcrituresRoute
  '/impayes': typeof ImpayesRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/regions': typeof RegionsRoute
  '/tresorerie': typeof TresorerieRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achats'
    | '/aide'
    | '/clients'
    | '/commerciaux'
    | '/ecritures'
    | '/impayes'
    | '/parametres'
    | '/produits'
    | '/recouvrement'
    | '/regions'
    | '/tresorerie'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achats'
    | '/aide'
    | '/clients'
    | '/commerciaux'
    | '/ecritures'
    | '/impayes'
    | '/parametres'
    | '/produits'
    | '/recouvrement'
    | '/regions'
    | '/tresorerie'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/achats'
    | '/aide'
    | '/clients'
    | '/commerciaux'
    | '/ecritures'
    | '/impayes'
    | '/parametres'
    | '/produits'
    | '/recouvrement'
    | '/regions'
    | '/tresorerie'
    | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsRoute: typeof AchatsRoute
  AideRoute: typeof AideRoute
  ClientsRoute: typeof ClientsRoute
  CommerciauxRoute: typeof CommerciauxRoute
  EcrituresRoute: typeof EcrituresRoute
  ImpayesRoute: typeof ImpayesRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  RecouvrementRoute: typeof RecouvrementRoute
  RegionsRoute: typeof RegionsRoute
  TresorerieRoute: typeof TresorerieRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recouvrement': {
      id: '/recouvrement'
      path: '/recouvrement'
      fullPath: '/recouvrement'
      preLoaderRoute: typeof RecouvrementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impayes': {
      id: '/impayes'
      path: '/impayes'
      fullPath: '/impayes'
      preLoaderRoute: typeof ImpayesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecritures': {
      id: '/ecritures'
      path: '/ecritures'
      fullPath: '/ecritures'
      preLoaderRoute: typeof EcrituresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerciaux': {
      id: '/commerciaux'
      path: '/commerciaux'
      fullPath: '/commerciaux'
      preLoaderRoute: typeof CommerciauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  AideRoute: AideRoute,
  ClientsRoute: ClientsRoute,
  CommerciauxRoute: CommerciauxRoute,
  EcrituresRoute: EcrituresRoute,
  ImpayesRoute: ImpayesRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  RecouvrementRoute: RecouvrementRoute,
  RegionsRoute: RegionsRoute,
  TresorerieRoute: TresorerieRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
